name: Approve Run — Ladbrokes

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: read
  issues: read

jobs:
  dispatch:
    if: contains(github.event.comment.body, '/run-ladbrokes') && github.event.issue.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: Ensure commenter has write/admin
        uses: actions/github-script@v7
        id: perm
        with:
          script: |
            const {owner, repo} = context.repo;
            const actor = context.payload.comment.user.login;
            const perm = await github.rest.repos.getCollaboratorPermissionLevel({ owner, repo, username: actor });
            const level = perm.data.permission;
            if (!['admin','maintain','write'].includes(level)) {
              core.setFailed(`@${actor} permission=${level} (need write/admin)`);
            } else {
              core.info(`@${actor} permitted: ${level}`);
            }

      - name: Trigger ladbrokes.yml (workflow_dispatch)
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: 'ladbrokes.yml',
              ref: 'main'
            });
            core.info('Dispatched ladbrokes.yml on main');
