name: Make Bets

on:
  workflow_dispatch:

jobs:
  make-bets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run daily model
        run: python -m src.run_daily

      - name: Fetch odds
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python -m src.odds_client \
            --sport auto \
            --regions au \
            --markets h2h \
            --date today \
            --out-dir data/odds \
            --api-key "$ODDS_API_KEY"

      - name: Make bets
        run: python -m src.make_bets --probs reports/latest/probabilities.csv --odds data/odds --out reports/latest/bets.csv

      - name: Upload bets
        uses: actions/upload-artifact@v4
        with:
          name: bets-report
          path: reports/latest/bets.csv
