name: Make Bets

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "05 23 * * *"   # optional: runs daily 23:05 UTC

permissions:
  contents: write

jobs:
  make-bets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run daily model (build probabilities.csv)
        run: python -m src.run_daily

      # Try to resolve a greyhound key from data/sports.json.
      # If not found, fall back to aussie_rules so the job still succeeds.
      - name: Resolve SPORT_KEY (prefer greyhounds, fallback to aussie_rules)
        id: sport
        shell: bash
        run: |
          set -e
          SPORT=""

          if [ -f data/sports.json ]; then
            SPORT=$(python - <<'PY'
import json,sys,re
with open("data/sports.json","r",encoding="utf-8") as f:
    data=json.load(f)
# Find any entry whose key or title mentions greyhound
key = None
for s in data:
    text = (s.get("key","")+" "+s.get("title","")).lower()
    if "greyhound" in text:
        key = s.get("key")
        break
if key:
    print(key)
PY
)
          fi

          # Fallback if nothing matched (Odds API has no greyhound endpoint)
          if [ -z "$SPORT" ]; then
            echo "[warn] No greyhound sport in sports.json; using aussie_rules"
            SPORT="aussie_rules"
          else
            echo "[info] Using sport key from sports.json: $SPORT"
          fi

          echo "SPORT_KEY=$SPORT" >> "$GITHUB_OUTPUT"

      - name: Fetch odds (Odds API)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          SPORT_KEY: ${{ steps.sport.outputs.SPORT_KEY }}
        run: |
          set -e
          mkdir -p data/odds
          echo "[info] Requesting odds for $SPORT_KEY"
          python -m src.odds_client \
            --api-key "$ODDS_API_KEY" \
            --sport "$SPORT_KEY" \
            --regions au \
            --markets h2h \
            --date today \
            --out-dir data/odds

      - name: Make bets (produce bets.csv)
        run: |
          python -m src.make_bets \
            --probs reports/latest/probabilities.csv \
            --odds data/odds \
            --out reports/latest/bets.csv

      - name: Upload bets artifact
        uses: actions/upload-artifact@v4
        with:
          name: bets-report
          path: reports/latest/bets.csv

      - name: Commit bets.csv back to repo
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "actions@github.com"
          git add reports/latest/bets.csv
          git commit -m "Add latest bets report" || echo "No changes to commit"
          git push
