name: Make Bets

on:
  workflow_dispatch:  # allows manual "Run workflow" button
  # schedule:
  #   - cron: "0 12 * * *"  # optional daily run at 12:00 UTC

permissions:
  contents: write

jobs:
  make-bets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily model (build probabilities.csv)
        run: python src/model.py --output data/probabilities.csv

      - name: Resolve greyhound SPORT_KEY from sports.json
        run: |
          sport=$(python - <<'PY'
import json
with open("data/sports.json") as f:
    sports = json.load(f)
for s in sports:
    if "greyhound" in s["key"]:
        print(s["key"])
        break
PY
          )
          if [ -z "$sport" ]; then
            echo "No greyhound sport found in sports.json"
            exit 1
          fi
          echo "SPORT_KEY=$sport" >> $GITHUB_ENV

      - name: Fetch odds (Odds API)
        run: |
          mkdir -p data/odds
          curl -s "https://api.the-odds-api.com/v4/sports/$SPORT_KEY/odds?apiKey=${{ secrets.ODDS_API_KEY }}&regions=au&markets=h2h&oddsFormat=decimal&dateFormat=iso" \
            -o data/odds/odds.json

      - name: Make bets (produce bets.csv)
        run: python src/make_bets.py --input data/probabilities.csv --odds data/odds/odds.json --output data/bets.csv

      - name: Upload bets artifact
        uses: actions/upload-artifact@v3
        with:
          name: bets
          path: data/bets.csv

      - name: Commit bets.csv back to repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add data/bets.csv
          git commit -m "Update bets.csv"
          git push
