name: Make Bets

on:
  workflow_dispatch:   # allows you to run manually
  schedule:
    - cron: "0 3 * * *"   # runs daily at 3:00 UTC (change as needed)

permissions:
  contents: write

jobs:
  make-bets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily model (build probabilities.csv)
        run: |
          python model.py --output data/probabilities.csv

      - name: Fetch odds (Odds API)
        run: |
          mkdir -p data/odds
          python odds_client.py \
            --api-key ${{ secrets.ODDS_API_KEY }} \
            --sport greyhound_racing_aus \
            --regions au \
            --markets h2h \
            --out-dir data/odds

      - name: Make bets (produce bets.csv)
        run: |
          python make_bets.py \
            --model data/probabilities.csv \
            --odds data/odds \
            --output bets.csv

      - name: Upload bets artifact
        uses: actions/upload-artifact@v4
        with:
          name: bets
          path: bets.csv

      - name: Commit bets.csv back to repo
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "actions@github.com"
          git add bets.csv
          git commit -m "Add daily bets.csv"
          git push
