name: Make Bets

on:
  workflow_dispatch:   # allows you to run it manually
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC (adjust if needed)

permissions:
  contents: write

jobs:
  make-bets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily model (build probabilities.csv)
        run: python src/model.py --output data/probabilities.csv

      - name: Resolve greyhound SPORT_KEY from sports.json
        id: sportkey
        run: |
          sport=$(python - <<'PY'
import json
with open("data/sports.json") as f:
    sports = json.load(f)
for s in sports:
    if "greyhound" in s["key"]:
        print(s["key"])
        break
PY
          )
          if [ -z "$sport" ]; then
            echo "No greyhound sport found in sports.json"
            exit 1
          fi
          echo "SPORT_KEY=$sport" >> $GITHUB_ENV

      - name: Fetch odds (Odds API)
        run: |
          mkdir -p data/odds
          curl -s "https://api.the-odds-api.com/v4/sports/${SPORT_KEY}/odds?apiKey=${{ secrets.ODDS_API_KEY }}&regions=au&markets=h2h&oddsFormat=decimal&dateFormat=iso" \
            -o data/odds/odds.json

      - name: Make bets (produce bets.csv)
        run: python src/make_bets.py --odds data/odds/odds.json --probs data/probabilities.csv --output data/bets.csv

      - name: Upload bets artifact
        uses: actions/upload-artifact@v4   # ✅ fixed version
        with:
          name: bets
          path: data/bets.csv

      - name: Commit bets.csv back to repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/bets.csv
          git commit -m "Update bets.csv"
          git push
