name: Make Bets

on:
  workflow_dispatch: {}             # run from the Actions tab
  schedule:
    - cron: "05 23 * * *"           # optional: 23:05 UTC daily

permissions:
  contents: write

jobs:
  make-bets:
    runs-on: ubuntu-latest
    env:
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      SPORT_KEY:    ${{ secrets.SPORT_KEY }}   # e.g. greyhound_racing_aus
      REGIONS: au
      MARKETS: h2h
      ODDS_FORMAT: decimal
      DATE_FORMAT: iso

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Prepare folders
        run: |
          set -euo pipefail
          mkdir -p data data/odds

      - name: Validate secrets
        run: |
          set -euo pipefail
          [ -n "${ODDS_API_KEY:-}" ] || { echo "::error::ODDS_API_KEY is not set"; exit 2; }
          [ -n "${SPORT_KEY:-}" ]    || { echo "::error::SPORT_KEY is not set";    exit 2; }

      - name: Fetch odds (TheOddsAPI)
        run: |
          set -euo pipefail
          URL="https://api.the-odds-api.com/v4/sports/${SPORT_KEY}/odds?apiKey=${ODDS_API_KEY}&regions=${REGIONS}&markets=${MARKETS}&oddsFormat=${ODDS_FORMAT}&dateFormat=${DATE_FORMAT}"
          echo "[info] Requesting: ${URL}"
          curl -fsSL "${URL}" -o data/odds/odds.json
          test -s data/odds/odds.json || { echo "::error::Empty odds response"; exit 2; }
          echo "[info] Saved -> data/odds/odds.json"

      - name: Run daily model (build probabilities.csv)
        run: |
          set -euo pipefail
          if [ -f "src/model.py" ]; then
            python src/model.py --output data/probabilities.csv || true
          else
            echo "[warn] src/model.py not found — skipping."
          fi

      - name: Make bets (produce bets.csv)
        run: |
          set -euo pipefail
          if [ -f "src/make_bets.py" ]; then
            python src/make_bets.py --odds data/odds/odds.json --output data/bets.csv
            test -s data/bets.csv
          else
            echo "::error::src/make_bets.py not found."
            exit 2
          fi

      - name: Upload bets artifact
        uses: actions/upload-artifact@v4
        with:
          name: bets
          path: data/bets.csv
          if-no-files-found: error
          retention-days: 7

      - name: Commit bets.csv back to repo (optional)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          set -euo pipefail
          git config --local user.email "actions@github.com"
          git config --local user.name  "actions-bot"
          git add data/bets.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "Update bets.csv (auto)"
            git push
          else
            echo "[info] No changes to commit."
          fi
