name: Daily greyhound scrape

on:
  schedule:
    - cron: "0 2 * * *"   # Runs every day 02:00 UTC
  workflow_dispatch: {}   # Manual run allowed

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: python scraper.py

      - name: Commit PDFs (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add forms/*.pdf || true
          if git diff --cached --quiet; then
            echo "No new PDFs to commit."
          else
            git commit -m "Add today's form PDFs"
            git push
          fi

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: form-pdfs
          path: forms/*.pdf
          if-no-files-found: warn
