name: Daily greyhound scrape

on:
  schedule:
    # Runs every day at 02:00 UTC (≈ 12:00 AEST/13:00 AEDT). Adjust if you like.
    - cron: "0 2 * * *"
  workflow_dispatch: {}   # allows manual run

permissions:
  contents: write   # required so the workflow can commit files

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto: daily scrape $(date -u +"%Y-%m-%d %H:%M:%S")"
            git push
          fi
