name: Fetch daily greyhound form PDFs

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Run date (YYYY-MM-DD or 'today')"
        required: false
        default: today
  schedule:
    # Runs every day at 06:05 Sydney time ( = 20:05 UTC the previous day )
    - cron: "5 20 * * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          RUN_DATE: ${{ github.event.inputs.date || 'today' }}
        run: |
          set -e
          mkdir -p forms
          echo "Fetching forms for: ${RUN_DATE}"
          if [ -f fetch_forms.py ]; then
            python fetch_forms.py --date "${RUN_DATE}" --out forms
          elif [ -f src/fetch_forms.py ]; then
            python -m src.fetch_forms --date "${RUN_DATE}" --out forms
          else
            echo "❌ fetch_forms.py not found (root or src/)."
            exit 1
          fi
          echo "Downloaded files:"
          ls -l forms || true

      - name: Commit PDFs (if any)
        run: |
          if [[ -n "$(git status --porcelain forms)" ]]; then
            git config user.name  "actions-user"
            git config user.email "actions@github.com"
            git add forms
            git commit -m "Add today's form PDFs"
            git push
          else
            echo "No new PDFs to commit."
          fi
