name: Greyhounds — Auto Discover & Scrape (Ladbrokes)

on:
  schedule:
    - cron: "30 01 * * *"  # runs 01:30 UTC daily (~11:30 AEST). Adjust if you like.
  workflow_dispatch: {}      # allows manual run from Actions tab

permissions:
  contents: write

concurrency:
  group: greyhounds-scrape
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # If Ladbrokes blocks default UA, we'll spoof one in the script.
      TIMEOUT_SECS: "30"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pandas
          python -m playwright install --with-deps chromium

      - name: Ensure data folder
        run: mkdir -p data

      - name: Auto-discover meetings and scrape odds
        run: |
          python -m src.ladbrokes_auto --out-dir data

      - name: Show first lines
        run: |
          echo "JSON preview:"
          head -n 40 data/greyhound_odds.json || true
          echo
          echo "CSV preview:"
          head -n 40 data/greyhound_odds.csv || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: greyhound-odds
          path: |
            data/greyhound_odds.json
            data/greyhound_odds.csv

      - name: Commit results to repo
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/greyhound_odds.json data/greyhound_odds.csv
          git commit -m "Daily greyhound odds (auto)" || echo "No changes"
          git push || true
