name: Odds API — List Sports

on:
  workflow_dispatch:

jobs:
  list-sports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Fetch sports from Odds API
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          mkdir -p data
          curl -s "https://api.the-odds-api.com/v4/sports/?apiKey=$ODDS_API_KEY" \
            | tee data/sports.json

      - name: Upload sports.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: sports-list
          path: data/sports.json

      - name: Commit sports.json back to repo
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "actions@github.com"
          git add data/sports.json
          git commit -m "Update sports list from Odds API"
          git push
