name: Greyhounds — Daily scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "10 4 * * *"   # 04:10 UTC (adjust if you like)

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 lxml pandas playwright
          fi

      # ✅ Let Playwright install the right system packages & Chromium itself
      - name: Install Playwright (browser + system deps)
        run: |
          python -m playwright install --with-deps chromium

      - name: Ensure output folders
        run: |
          mkdir -p data/rns data/thedogs data/combined

      - name: Racing & Sports — scrape
        run: |
          python src/rns_daily.py --out-dir data/rns

      - name: TheDogs — scrape (fallback source)
        run: |
          python src/thedogs_daily.py --out-dir data/thedogs

      - name: Merge to one CSV
        run: |
          python src/merge_daily.py --rns data/rns --dogs data/thedogs --out data/combined

      - name: Show previews
        if: always()
        run: |
          echo "=== R&S ==="; ls -lah data/rns || true; tail -n +1 -v data/rns/* 2>/dev/null | head -n 120 || true
          echo "=== TheDogs ==="; ls -lah data/thedogs || true; tail -n +1 -v data/thedogs/* 2>/dev/null | head -n 120 || true
          echo "=== Combined ==="; ls -lah data/combined || true; tail -n +1 -v data/combined/* 2>/dev/null | head -n 120 || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: greyhounds-data
          path: |
            data/**/*
          if-no-files-found: warn

      - name: Commit results
        if: always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A data || true
          git commit -m "Daily scrape $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nothing to commit"
          git push || echo "No changes to push"
