name: Greyhounds — Daily scrape

on:
  workflow_dispatch:
  schedule:
    # 06:05 AEST daily
    - cron: '5 20 * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure output folders
        run: |
          mkdir -p forms
          mkdir -p reports/latest

      - name: Racing & Sports — fetch PDFs
        env:
          TZ: Australia/Sydney
        run: |
          python -u src/rns_daily.py --out forms

      - name: Build summary
        run: |
          python -u src/merge_daily.py --forms forms --out reports/latest

      - name: Show summary preview
        if: success()
        run: |
          echo "==== reports/latest/summary.md ===="
          cat reports/latest/summary.md || true
          echo
          echo "==== forms/ (ls) ===="
          ls -la forms

      - name: Commit results
        if: success()
        run: |
          git config --local user.email "actions[bot]@users.noreply.github.com"
          git config --local user.name "actions-user"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            msg="chore: update forms and summary ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git commit -m "$msg"
            git push
          fi
