name: Greyhounds — Daily scrape

on:
  workflow_dispatch:
  schedule:
    # 08:00 AEST every day (23:00 UTC previous day)
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure folders
        run: |
          mkdir -p forms data/rns reports/latest

      - name: Fetch + Parse + Report
        env:
          TZ: Australia/Sydney
        run: |
          python src/run_daily.py --out-forms forms --out-rns data/rns --out-reports reports

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: greyhounds-data
          path: |
            forms/*.pdf
            data/rns/*.csv
            reports/latest/*

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "daily: fetch+parse+report"
            git push
          fi
