name: Greyhounds — Daily scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "05 6 * * *"  # 6:05 UTC daily; adjust to your preference

jobs:
  scrape:
    # If you set up a self-hosted AU runner, uncomment next 2 lines:
    # runs-on: self-hosted
    # labels: [linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      PYTHONUNBUFFERED: "1"
      PROXY_URL: ${{ secrets.PROXY_URL }}  # optional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure output folders
        run: |
          mkdir -p data/rns data/thedogs data/combined forms reports/latest

      - name: Racing & Sports — discover PDFs
        run: |
          python -m src.rns_daily || true

      - name: TheDogs — discover meetings (fallback)
        run: |
          python -m src.thedogs_daily || true

      - name: Download PDFs
        run: |
          python -m src.fetch_forms || true

      - name: Parse PDFs to CSV
        run: |
          python -m src.parse_pdf || true

      - name: Make picks & reports
        run: |
          python -m src.make_bets || true

      - name: Show previews
        run: |
          echo "--- latest combined ---"
          ls -la data/combined || true
          echo "--- latest forms ---"
          ls -la forms | tail -n 20 || true
          echo "--- reports/latest ---"
          ls -la reports/latest || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: greyhounds-data
          path: |
            data/**
            forms/**
            reports/latest/**

      - name: Commit results to repo
        run: |
          git config --local user.email "actions-user@users.noreply.github.com"
          git config --local user.name "actions-user"
          git add -A
          git commit -m "daily: data & reports $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "Nothing to commit"
          git push || echo "Nothing to push"
